from __future__ import annotations

from typing import Optional, Protocol

from app.schemas import AuditEvent, FormDecision, OrderForm, TrainingRecord
from app.trust.ledger import LedgerStat


class Store(Protocol):
    # 帳票
    def put_form(self, fd: FormDecision, image: bytes) -> None: ...
    def get_form(self, form_id: str) -> Optional[FormDecision]: ...
    def get_image(self, form_id: str) -> Optional[bytes]: ...
    def list_pending(self, limit: int = 50) -> list[FormDecision]: ...
    def list_forms(self, limit: int = 200) -> list[FormDecision]: ...
    # 過去の確定例（few-shot 用）
    def recent_confirmed(self, sender_id: str, format_id: str, limit: int = 3) -> list[tuple[str, OrderForm]]: ...
    # 台帳
    def get_ledger(self, key: str) -> Optional[LedgerStat]: ...
    def put_ledger(self, stat: LedgerStat) -> None: ...
    def list_ledger(self) -> list[LedgerStat]: ...
    # 教師データ
    def add_training(self, recs: list[TrainingRecord]) -> None: ...
    def list_training(self, limit: int = 100_000) -> list[TrainingRecord]: ...
    def count_training(self) -> int: ...
    # 監査
    def add_audit(self, ev: AuditEvent) -> None: ...
    def list_audit(self, form_id: Optional[str] = None, limit: int = 200) -> list[AuditEvent]: ...
    # 振り返り: 提案・承認済みルール・ポリシー上書き
    def put_proposal(self, p) -> None: ...
    def get_proposal(self, proposal_id: str): ...
    def list_proposals(self, status: Optional[str] = None, limit: int = 100) -> list: ...
    def put_rule(self, rule) -> None: ...
    def list_rules(self, scope: Optional[str] = None) -> list: ...
    def put_policy_override(self, key: str, value) -> None: ...
    def get_policy_overrides(self) -> dict: ...
